[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20"

[[redirects]]
  from = "/"
  to = "/app/inicio"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
